### ISSUE TITLE
Devices failing to load

### ISSUE THREAD

**Issue by MurryMcIntosh** [pradeepmouli/homebridge-isy-js#18]
Just hooked up my homebridge and started messing around. I noticed that only my scenes were showing up, so I thought maybe that was default behavior. Then I noticed that ONE of my Insteon switches was getting loaded, so I went back through the homebridge logs and found an error. From here I can see that one switch device DOES get loaded, and then an error is thrown and homebridge-isy skips to loading scenes. I'd rather have my devices so I have dimming capabilities and then exclude scenes.

[5/23/2020, 10:11:35 PM] Homebridge is running on port 51943.
[5/23/2020, 10:11:35 PM] [WizSmarthome] New Device Online: [a8bb50f29c08] bulb [a8bb50f29c08] 192.168.0.175 49156
[5/23/2020, 10:11:35 PM] [WizSmarthome] Adding: [a8bb50f29c08] bulb [a8bb50f29c08]
[5/23/2020, 10:11:35 PM] [ISY] platform config saved to : /var/lib/homebridge/effectiveConfig.json
[5/23/2020, 10:11:35 PM] [isy-nodejs] Sending request: http://192.168.0.135:5035/rest/nodes/
Calling: http://192.168.0.135:5035/rest/nodes/
[5/23/2020, 10:11:35 PM] [isy-nodejs] null
[5/23/2020, 10:11:36 PM] [isy-nodejs] Loading Folders
[5/23/2020, 10:11:36 PM] [isy-nodejs] Loading Devices
[5/23/2020, 10:11:36 PM] [isy-nodejs] Main Floor Back Hall 2 (4B 11 7A 1): RelayLampSwitch_ADV
[5/23/2020, 10:11:36 PM] [isy-nodejs] Main Floor Back Hall 2 (4B 11 7A 1): Property Status (ST) initialized to: 0 (Off)
[5/23/2020, 10:11:36 PM] [isy-nodejs] Sending request: http://192.168.0.135:5035/rest/nodes/4B 11 7A 1/notes/
Calling: http://192.168.0.135:5035/rest/nodes/4B 11 7A 1/notes/
[5/23/2020, 10:11:36 PM] [isy-nodejs] null
[5/23/2020, 10:11:36 PM] [isy-nodejs] Main Floor Back Hall 2 (4B 11 7A 1): No notes found.
[5/23/2020, 10:11:36 PM] [isy-nodejs] Main Floor Back Hall 2 (4B 11 7A 1): Display name format: ${location ?? folder} ${spokenName ?? name}
[5/23/2020, 10:11:36 PM] [isy-nodejs] Main Floor Back Hall 2 (4B 11 7A 1): Template format updated to: ${this.location === null || this.location === undefined || this.location === '' ? this.folder : this.location} ${this.spokenName === null || this.spokenName === undefined || this.spokenName === '' ? this.name : this.spokenName}
[5/23/2020, 10:11:36 PM] [isy-nodejs] Main Floor Back Hall 2 (4B 11 7A 1): The friendly name updated to: Main Floor Back  Hall 2
[5/23/2020, 10:11:36 PM] [isy-nodejs] Error Loading Devices TypeError: Cannot read property 'class' of null
    at Function.getNLSSwitchLightInfo (/usr/lib/node_modules/homebridge-isy/node_modules/isy-nodejs/lib/Devices/Insteon/InsteonDeviceFactory.js:276:20)
    at Function.getInsteonDeviceDetails (/usr/lib/node_modules/homebridge-isy/node_modules/isy-nodejs/lib/Devices/Insteon/InsteonDeviceFactory.js:45:50)
    at Function.getDeviceDetails (/usr/lib/node_modules/homebridge-isy/node_modules/isy-nodejs/lib/Devices/DeviceFactory.js:10:64)
    at ISY.loadDevices (/usr/lib/node_modules/homebridge-isy/node_modules/isy-nodejs/lib/ISY.js:209:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ISY.loadNodes (/usr/lib/node_modules/homebridge-isy/node_modules/isy-nodejs/lib/ISY.js:159:13)
    at ISY.initialize (/usr/lib/node_modules/homebridge-isy/node_modules/isy-nodejs/lib/ISY.js:421:13)
    at ISYPlatform.createAccessories (/usr/lib/node_modules/homebridge-isy/src/ISYPlatform.ts:236:3)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-isy/src/ISYPlatform.ts:69:4)
[5/23/2020, 10:11:36 PM] [isy-nodejs] Loading Scenes
....

**Comment by MurryMcIntosh** [comment]
Woke up this morning and found that non of my Homebridge lights are responding to the Homekit app anymore. Restarting Homebridge still brings up the same errors as above, but now the Home app does not control anything. Strangely, if I turn on or off a light in the Home app it shows that the light was turned "on" or "off", but the light itself does not change, nor are any messages output by Homebridge logs. When changing lights physically or through ISY admin console, Homebridge outputs it's normal logs.

**Comment by pradeepmouli** [comment]
Thanks - can u send me the your isynodesdump.json? It is in the same folder as your homebridge config.json
