### ISSUE TITLE
GarageDoor -  this.device.getCurrentDoorWindowState is not a function

### ISSUE THREAD

**Issue by cswelin** [pradeepmouli/homebridge-isy-js#28]
I'm getting the following on start of `Homebridge` which appears to make it so no device is added to `HomeKit`

```
UnhandledPromiseRejectionWarning: TypeError: this.device.getCurrentDoorWindowState is not a function
at ISYGarageDoorAccessory.getSensorState (/usr/local/lib/node_modules/homebridge-isy/src/ISYGarageDoorAccessory.ts:34:23)
at new ISYGarageDoorAccessory (/usr/local/lib/node_modules/homebridge-isy/src/ISYGarageDoorAccessory.ts:20:12)
at /usr/local/lib/node_modules/homebridge-isy/src/ISYPlatform.ts:279:23
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at ISYPlatform.createAccessories (/usr/local/lib/node_modules/homebridge-isy/src/ISYPlatform.ts:236:3)
at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-isy/src/ISYPlatform.ts:69:4)
```

[ISYNodesDump.zip](https://github.com/pradeepmouli/homebridge-isy-js/files/4831916/ISYNodesDump.zip)

**Comment by cswelin** [comment]
Reinstall everything seemed to have fixed this.
