### ISSUE TITLE
ISY Failed To Load

### ISSUE THREAD

**Issue by dfwwingnut** [pradeepmouli/homebridge-isy-js#31]
Just getting started with Homebridge-ISY.  Can't get it to load.  It always seems to error out while parsing the variables node.  Any suggestions?

Calling: https://192.168.2.10/rest/vars/get/1/
[7/8/2020, 12:03:38] [isy-nodejs] Sending request: https://192.168.2.10/rest/vars/definitions/2/
Calling: https://192.168.2.10/rest/vars/definitions/2/
[7/8/2020, 12:03:38] [isy-nodejs] Error initializing ISY: {}
[7/8/2020, 12:03:38] [isy-nodejs] Connecting to: ws://192.168.2.10/rest/subscribe
[7/8/2020, 12:03:38] [ISY] Accessories to configure: 0

**Comment by canz78** [comment]
same issue here any ideas 
Hello I am running into a issue after i start the hb service. Looking at the log I see this error. 

[8/5/2020, 3:49:54 AM] [isy-nodejs] Error initializing ISY: {}
[8/5/2020, 3:49:54 AM] [isy-nodejs] Connecting to: ws://192.168.50.16/rest/subscribe
[8/5/2020, 3:49:54 AM] [ISY] Accessories to configure: 0
[8/5/2020, 3:49:54 AM] [ISY] ISY has 43 devices and 16 scenes
(node:6569) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'lastAddressDigit' of undefined
    at Object.isMatch (/usr/lib/node_modules/homebridge-isy/src/utils.ts:25:13)
    at /usr/lib/node_modules/homebridge-isy/src/ISYPlatform.ts:244:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ISYPlatform.createAccessories (/usr/lib/node_modules/homebridge-isy/src/ISYPlatform.ts:236:3)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-isy/src/ISYPlatform.ts:69:4)
(node:6569) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6569) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by braddunlap** [comment]
running into the same problem... my guess is it has to do with a node update, but not sure what the issue is. Homebridge does continue to load the devices in the log within Homebridge and I can see their statuses change within the Homebridge log, but the devices don't show up in HomeKit.

**Comment by pradeepmouli** [comment]
Please try RC23. This may fix.
