### ISSUE TITLE
Doesn't work in HOOBS3

### ISSUE THREAD

**Issue by nathanjskelton** [pradeepmouli/homebridge-isy-js#5]
Installed in HOOBS3 replacing the rodtoll version... starts up with "The requested platform 'ISY' was not registered by any plugin". Reverting to the rodtoll version fixes.

**Comment by pradeepmouli** [comment]
Should have a fix in the next day or 2.

**Comment by pradeepmouli** [comment]
Should work now. Please let me know - you'll have to change the platform/platform name to "ISY" from "isy-js".

**Comment by kavehv** [comment]
> Should work now. Please let me know - you'll have to change the platform/platform name to "ISY" from "isy-js".

Should the readme be updated to reflect this?

**Comment by pradeepmouli** [comment]
Yes - thanks.

**Comment by nathanjskelton** [comment]
last time i made the switch my homekit and alexa devices reset-- is there a
way that you know of to switch from the rodtoll version to yours without
disrupting the setup? I have about 70 devices so it's a pain...

**Comment by pradeepmouli** [comment]
You need to upgrade to homebridge@beta

**Comment by kavehv** [comment]
> You need to upgrade to homebridge@beta
> […](#)

Any chance you could update the README.md with these requirements?

**Comment by pradeepmouli** [comment]
I think it’s on there

**Comment by kavehv** [comment]
> I think it’s on there
> […](#)
homebridge@beta is, but the name/platform changes seem to be the old ones in the sample config in it.

**Comment by nathanjskelton** [comment]
Still getting error loading in HOOBS3/docker:

Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]: [Homebridge] [4/29/2020, 1:45:36 PM] Error loading plugin "homebridge-isy".
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]: [Homebridge] [4/29/2020, 1:45:36 PM] Error: Cannot find module 'homebridge/lib/platformAccessory'
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]: Require stack:
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]: - /hoobs/node_modules/homebridge-isy/dist/plugin.js
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]: - /usr/src/hoobs/lib/bridge/plugin.js
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]: - /usr/src/hoobs/lib/bridge/server.js
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]: - /usr/src/hoobs/lib/bridge/cli.js
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]: - /usr/src/hoobs/lib/bridge/bin/homebridge
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Module.require (internal/modules/cjs/loader.js:1044:19)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at require (internal/modules/cjs/helpers.js:77:18)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Object.<anonymous> (/hoobs/node_modules/homebridge-isy/dist/plugin.js:7:29)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Module.load (/hoobs/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Module.require (internal/modules/cjs/loader.js:1044:19)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at require (internal/modules/cjs/helpers.js:77:18)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Plugin.load (/usr/src/hoobs/lib/bridge/plugin.js:46:27)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Server.<anonymous> (/usr/src/hoobs/lib/bridge/server.js:159:20)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Array.forEach (<anonymous>:null:null)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Server._loadPlugins (/usr/src/hoobs/lib/bridge/server.js:153:24)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at new Server (/usr/src/hoobs/lib/bridge/server.js:66:26)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at module.exports (/usr/src/hoobs/lib/bridge/cli.js:43:20)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Object.<anonymous> (/usr/src/hoobs/lib/bridge/bin/homebridge:27:59)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Module.load (internal/modules/cjs/loader.js:1002:32)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Apr 29 09:45:36 ubuntu01 ead8c5b7b9aa[30215]:     at internal/main/run_main_module.js:18:47

**Comment by pradeepmouli** [comment]
Okay - will take a look

**Comment by pradeepmouli** [comment]
try now. I changed the location it uses to search for homebridge, since it the docker image doesn't support global installs.

**Comment by nathanjskelton** [comment]
no dice 

Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]: [Homebridge] [4/30/2020, 1:45:46 PM] Error loading plugin "homebridge-isy".
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]: [Homebridge] [4/30/2020, 1:45:46 PM] Error: Cannot find module '/usr/local/lib/node_modules/homebridge'
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]: Require stack:
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]: - /hoobs/node_modules/homebridge-isy/dist/plugin.js
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]: - /usr/src/hoobs/lib/bridge/plugin.js
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]: - /usr/src/hoobs/lib/bridge/server.js
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]: - /usr/src/hoobs/lib/bridge/cli.js
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]: - /usr/src/hoobs/lib/bridge/bin/homebridge
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Module.require (internal/modules/cjs/loader.js:1044:19)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at require (internal/modules/cjs/helpers.js:77:18)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Object.<anonymous> (/hoobs/node_modules/homebridge-isy/dist/plugin.js:7:22)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Module.load (/hoobs/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Module.require (internal/modules/cjs/loader.js:1044:19)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at require (internal/modules/cjs/helpers.js:77:18)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Plugin.load (/usr/src/hoobs/lib/bridge/plugin.js:46:27)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Server.<anonymous> (/usr/src/hoobs/lib/bridge/server.js:159:20)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Array.forEach (<anonymous>:null:null)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Server._loadPlugins (/usr/src/hoobs/lib/bridge/server.js:153:24)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at new Server (/usr/src/hoobs/lib/bridge/server.js:66:26)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at module.exports (/usr/src/hoobs/lib/bridge/cli.js:43:20)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Object.<anonymous> (/usr/src/hoobs/lib/bridge/bin/homebridge:27:59)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Module.load (internal/modules/cjs/loader.js:1002:32)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:     at internal/main/run_main_module.js:18:47
Apr 30 09:45:46 ubuntu01 ead8c5b7b9aa[30215]:

**Comment by nathanjskelton** [comment]
Any update on getting this to work with HOOBS3?
