### ISSUE TITLE
Path/include issues in offical Docker homebidge image install

### ISSUE THREAD

**Issue by apnar** [pradeepmouli/homebridge-isy-js#7]
When installing this plugin in the official homebridge docker install here:

https://hub.docker.com/r/oznu/homebridge/

The plugin can't start due to not being able to find some includes.  Tweaking the following paths manually "fixes" it but obviously isn't the correct solution:

cd node_modules/homebridge-isy/dist
sed -i 's#homebridge/#/usr/local/lib/node_modules/homebridge/#' *

I unfortunately don't know node well enough to suggest a proper fix.  Also it doesn't have permission to write to where ever it's trying to write the ISYNodesDump.json file.  I added /tmp/ in front of those paths to get it put there.

**Comment by apnar** [comment]
FYI, logs from the homebridge

`[4/28/2020, 9:24:55 PM] [HB Supervisor] Starting Homebridge with extra flags: -P /homebridge/node_modules -D
[4/28/2020, 9:24:55 PM] [HB Supervisor] Started Homebridge with PID: 1723
[4/28/2020, 9:24:55 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/28/2020, 9:24:55 PM] ---
[4/28/2020, 9:24:55 PM] Loaded plugin: homebridge-dummy
[4/28/2020, 9:24:55 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[4/28/2020, 9:24:55 PM] ---
[4/28/2020, 9:24:55 PM] ====================
[4/28/2020, 9:24:55 PM] ERROR LOADING PLUGIN homebridge-isy:
[4/28/2020, 9:24:55 PM] Error: Cannot find module 'homebridge/lib/platformAccessory'
Require stack:
- /homebridge/node_modules/homebridge-isy/dist/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/index.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-isy/dist/plugin.js:7:29)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
[4/28/2020, 9:24:55 PM] ====================
[4/28/2020, 9:24:55 PM] Loaded plugin: homebridge-config-ui-x
[4/28/2020, 9:24:55 PM] Registering platform 'homebridge-config-ui-x.config'
[4/28/2020, 9:24:55 PM] ---
[4/28/2020, 9:24:55 PM] Loading 1 platforms...
[4/28/2020, 9:24:55 PM] Error loading platform requested in your config.json at position 1
[4/28/2020, 9:24:55 PM] Error: The requested platform 'ISY' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
[4/28/2020, 9:24:55 PM] [HB Supervisor] Homebridge Process Ended. Code: 0, Signal: null`

**Comment by pradeepmouli** [comment]
try now. I changed the location it uses to search for homebridge, since it the docker image doesn't support global installs.

**Comment by apnar** [comment]
Latest version fixes the includes, thanks!  So now you can do the install inside the Docker container and everything works as it should.

There is still an error trying to write out ISYNodesDump.json, but that's much less important.  Ideally in the Docker install it'd write to /homebridge as that's what's mapped outside the container, but that isn't universal.  I'd expect /tmp should work most places.

**Comment by pradeepmouli** [comment]
try the latest update - homebridge-isy imports homebridge & hap-nodesjs as modules. I've added a post install script that tries to find the installation path of homebridge and hap-nodes, wherever it is, and updates the source files. So it should support the standard image as well as others.

**Comment by apnar** [comment]
Just tested with v0.5.0-beta.23 (2020-04-30) and the install fails.  I suspect the issue is you are trying to run bash which isn't installed in the container.  I'd suggest just using 'sh'.

**Comment by pradeepmouli** [comment]
try now, fixed the ignore issue + stopped using the shell script altogether.

**Comment by apnar** [comment]
Thanks so much!  v0.5.0-beta.24 installs ok in the official docker image and the ignore rules now seem to be taking effect.  I'll do more testing when I get a chance but only obvious remaining error is where it's trying to write ISYNodesDump.json file which doesn't impact functionality.

**Comment by pradeepmouli** [comment]
okay - will work on that. beta.26 for your testing. I added support for the keypad buttons to trigger events within HomeKit.

**Comment by apnar** [comment]
Version  v0.5.0-rc2 fixes the path issue for node dump (and other new related files).  Thanks!

**Comment by pradeepmouli** [comment]
okay - try RC3…. By the way, a few other things are configurable too, e.g. the device naming convention. Let me know if that works. I will update the readme for the same soon.
